### PR TITLE
Update node from node12 to node16

### PR DESCRIPTION
**Pull request by bigearsenal**

### CODE REVIEW

**Comment by d3li0n** [comment]
Would be a really helpful release.

**Comment by maciejp** [comment]
Thanks for opening the PR, you beat me to it 😉 I think it might be nice to mention why it's important to do it:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

**Review by davereid-pfg — APPROVED** [review]

**Comment by john-doherty** [comment]
HI @davereid-pfg who else need to approve these changes? Keen to get this live

**Comment by davereid-pfg** [comment]
I'm not a maintainer so they would need to approve them.

**Comment by sebastiankugler** [comment]
This is the first of three PRs to update to node 16. It suggests a version number 0.6.0, which I like because I see it as a feature release rather than a bugfix as suggested in #138.

I think it would be good though to update also the version number in package.json as suggested by @sfullerbeckman in #138.

**Comment by mpdude** [comment]
Released 0.6.0. Thank you all for your suggestions and patience!

**Pull request merged**
